---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-preview-pr-pipeline
spec:
  params:
    - name: head-branch
      description: source branch of the PR
    - name: head-sha
      description: commit id
    - name: head-repo
      description: the name of the PR's repo source
    - name: base-branch
      description: target branch of the PR
    - name: base-repo
      description: target branch of the PR
    - name: base-repo-name
      description: name of the base repo
    - name: base-repo-owner
      description: owner of the base repo
    - name: pr-url
      description: PR url
    - name: commit-timestamp
      description: the timestamp of when the commit pushed

    - name: repository-integration
      description: the repo integration name
    - name: compliance-baseimage
      description: one-pipeline baseimage to run most of the built-in pipeline code
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"

  workspaces:
    - name: artifacts

  tasks:
    - name: code-pr-start
      taskRef:
        name: pr-start
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: commit-timestamp
          value: $(params.commit-timestamp)
        - name: pr-url
          value: $(params.pr-url)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: setup

    - name: code-setup
      taskRef:
        name: run-stage
      runAfter:
        - code-pr-start
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: setup
        - name: image
          value: $(tasks.code-pr-start.results.image)
        - name: script
          value: $(tasks.code-pr-start.results.script)
        - name: configmap
          value: $(tasks.code-pr-start.results.configmap)
        - name: secret
          value: $(tasks.code-pr-start.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-pr-start.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-pr-start.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-pr-start.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: test
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)

    - name: code-unit-tests
      taskRef:
        name: run-stage
      runAfter:
        - code-setup
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: test
        - name: image
          value: $(tasks.code-setup.results.image)
        - name: script
          value: $(tasks.code-setup.results.script)
        - name: configmap
          value: $(tasks.code-setup.results.configmap)
        - name: secret
          value: $(tasks.code-setup.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-setup.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-setup.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-setup.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: next-stage
          value: containerize

    - name: build-containerize
      taskRef:
        name: run-stage
      runAfter:
        - code-unit-tests
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: containerize
        - name: image
          value: $(tasks.code-unit-tests.results.image)
        - name: script
          value: $(tasks.code-unit-tests.results.script)
        - name: configmap
          value: $(tasks.code-unit-tests.results.configmap)
        - name: secret
          value: $(tasks.code-unit-tests.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-unit-tests.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-unit-tests.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-unit-tests.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: next-stage
          value: scan-artifact

    - name: build-scan-artifact
      taskRef:
        name: run-stage
      runAfter:
        - build-containerize
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: scan-artifact
        - name: image
          value: $(tasks.build-containerize.results.image)
        - name: script
          value: $(tasks.build-containerize.results.script)
        - name: configmap
          value: $(tasks.build-containerize.results.configmap)
        - name: secret
          value: $(tasks.build-containerize.results.secret)
        - name: abort-on-failure
          value: $(tasks.build-containerize.results.abort-on-failure)
        - name: dind
          value: $(tasks.build-containerize.results.dind)
        - name: image-pull-policy
          value: $(tasks.build-containerize.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: next-stage
          value: deploy-app-preview

    - name: deploy-app-preview
      taskRef:
        name: run-stage
      runAfter:
        - build-scan-artifact
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: deploy-app-preview
        - name: image
          value: $(tasks.build-scan-artifact.results.image)
        - name: script
          value: $(tasks.build-scan-artifact.results.script)
        - name: configmap
          value: $(tasks.build-scan-artifact.results.configmap)
        - name: secret
          value: $(tasks.build-scan-artifact.results.secret)
        - name: abort-on-failure
          value: $(tasks.build-scan-artifact.results.abort-on-failure)
        - name: dind
          value: $(tasks.build-scan-artifact.results.dind)
        - name: image-pull-policy
          value: $(tasks.build-scan-artifact.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: next-stage
          value: acceptance-test

    - name: deploy-acceptance-tests
      taskRef:
        name: run-stage
      runAfter:
        - deploy-app-preview
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: acceptance-test
        - name: image
          value: $(tasks.deploy-app-preview.results.image)
        - name: script
          value: $(tasks.deploy-app-preview.results.script)
        - name: configmap
          value: $(tasks.deploy-app-preview.results.configmap)
        - name: secret
          value: $(tasks.deploy-app-preview.results.secret)
        - name: abort-on-failure
          value: $(tasks.deploy-app-preview.results.abort-on-failure)
        - name: dind
          value: $(tasks.deploy-app-preview.results.dind)
        - name: image-pull-policy
          value: $(tasks.deploy-app-preview.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)

    - name: code-pr-finish
      runAfter:
        - deploy-acceptance-tests
      taskRef:
        name: pr-finish
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

  finally:
    - name: app-preview-pr-finish
      taskRef:
        name: app-preview-pr-finish
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: containerize-state
          value: "$(tasks.build-containerize.status)"
        - name: scan-artifact-state
          value: "$(tasks.build-scan-artifact.status)"
        - name: app-preview-state
          value: "$(tasks.deploy-app-preview.status)"
        - name: acceptance-tests-state
          value: "$(tasks.deploy-acceptance-tests.status)"
        - name: pr-pipeline-state
          value: "$(tasks.code-pr-finish.status)"
        - name: pipeline-debug
          value: $(params.pipeline-debug)
