---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pr-pipeline
spec:
  params:
    - name: head-branch
      description: source branch of the PR
    - name: head-sha
      description: commit id
    - name: head-repo
      description: the name of the PR's repo source
    - name: base-branch
      description: target branch of the PR
    - name: base-repo
      description: target branch of the PR
    - name: base-repo-name
      description: name of the base repo
    - name: base-repo-owner
      description: owner of the base repo
    - name: pr-url
      description: PR url
    - name: commit-timestamp
      description: the timestamp of when the commit pushed
    - name: repository-integration
      description: the repo integration name
    - name: compliance-baseimage
      description: one-pipeline baseimage to run most of the built-in pipeline code
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: dind-image
      default: "wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/docker:19-dind"
    - name: detect-secrets-image
      default: "wcp-cd-noncontainerised-team-cd-non-container-base-docker-local.artifactory.swg-devops.com/detect-secrets:0.13.1.ibm.34.dss@sha256:ba9ca6517c5abad09e3e1356c77b6b16d8d4f52ea2bab7e35a2296aee9f23131" 

  workspaces:
    - name: artifacts

  tasks:
    - name: code-pr-start
      taskRef:
        name: pr-start
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: commit-timestamp
          value: $(params.commit-timestamp)
        - name: pr-url
          value: $(params.pr-url)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: setup

    - name: code-setup
      taskRef:
        name: run-stage
      runAfter:
        - code-pr-start
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: setup
        - name: image
          value: $(tasks.code-pr-start.results.image)
        - name: script
          value: $(tasks.code-pr-start.results.script)
        - name: configmap
          value: $(tasks.code-pr-start.results.configmap)
        - name: secret
          value: $(tasks.code-pr-start.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-pr-start.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-pr-start.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-pr-start.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: test
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: dind-image
          value: $(params.dind-image)
    - name: code-unit-tests
      taskRef:
        name: run-stage
      runAfter:
        - code-setup
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: test
        - name: image
          value: $(tasks.code-setup.results.image)
        - name: script
          value: $(tasks.code-setup.results.script)
        - name: configmap
          value: $(tasks.code-setup.results.configmap)
        - name: secret
          value: $(tasks.code-setup.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-setup.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-setup.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-setup.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: head-branch
          value: $(params.head-branch)
        - name: head-sha
          value: $(params.head-sha)
        - name: head-repo
          value: $(params.head-repo)
        - name: base-branch
          value: $(params.base-branch)
        - name: base-repo
          value: $(params.base-repo)
        - name: base-repo-name
          value: $(params.base-repo-name)
        - name: base-repo-owner
          value: $(params.base-repo-owner)
        - name: dind-image
          value: $(params.dind-image)
    - name: code-pr-finish
      runAfter:
        - code-unit-tests
      taskRef:
        name: pr-finish
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: detect-secrets-image
          value: $(params.detect-secrets-image)
