apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: code-setup-pipeline-env
spec:
  params:
    - name: one-pipeline-config-branch
    - name: one-pipeline-config-repo
    - name: repository-branch
    - name: pipeline-debug
      default: "0"
  results:
    - name: repository-url
    - name: one-pipeline-repo-url
    - name: one-pipeline-repo-branch
  volumes:
    - name: cd-config
      configMap:
        name: toolchain
  steps:
    - name: setup
      image: ibmcom/pipeline-base-image:2.6@sha256:7f588468622a981f89cf5e1212aaf75fface9da6169b5345ca52ab63d8215907
      volumeMounts:
        - name: cd-config
          mountPath: /cd-config
      env:
        - name: ONE_PIPELINE_CONFIG_BRANCH
          value: $(params.one-pipeline-config-branch)
        - name: ONE_PIPELINE_CONFIG_REPO
          value: $(params.one-pipeline-config-repo)
        - name: APP_REPO_BRANCH
          value: $(params.repository-branch)
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      script: |
        #!/bin/bash

        if [[ "$PIPELINE_DEBUG" == 1 ]]; then
          trap env EXIT
          set -x
        fi

        APP_REPO=$(jq -j '.services[] | select(.toolchain_binding.name=="app-repo") | .dashboard_url' /cd-config/toolchain.json)
        ONE_PIPELINE_REPO="${ONE_PIPELINE_CONFIG_REPO:=$APP_REPO}"
        ONE_PIPELINE_BRANCH="${ONE_PIPELINE_CONFIG_BRANCH:=$APP_REPO_BRANCH}"

        echo -n "$APP_REPO" > "$(results.repository-url.path)"
        echo -n "$ONE_PIPELINE_REPO" > "$(results.one-pipeline-repo-url.path)"
        echo -n "$ONE_PIPELINE_BRANCH" > "$(results.one-pipeline-repo-branch.path)"
