---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: branch
      description: branch
    - name: target-branch
      description: target branch
    - name: repository-integration
      description: the repo integration name
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: the timestamp of when the commit pushed
    - name: slack-notifications
      description: toggles slack notifications
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: pr-url
      description: PR url
    - name: pr-repository
      description: the repo with as PR source
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: onepipeline-dockerconfigjson
      description: dockerconfigjson for images used in .one-pipeline.yaml
      default: "eyJhdXRocyI6e319" # ie. {"auths":{}} base64 encoded
    - name: one-pipeline-config
      description: Configuration file to be used to customize pipeline behavior
      default: .one-pipeline.yaml
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.onepipeline-dockerconfigjson)
      metadata:
        name: onepipeline-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
        - name: onepipeline-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        serviceAccountName: sa-pullsecret
        params:
          - name: branch
            value: $(params.branch)
          - name: target-branch
            value: $(params.target-branch)
          - name: repository-integration
            value: $(params.repository-integration)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: commit-id
            value: $(params.commit-id)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: slack-notifications
            value: $(params.slack-notifications)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: pr-url
            value: $(params.pr-url)
          - name: one-pipeline-config
            value: $(params.one-pipeline-config)
