---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pr-finish
spec:
  params:
    - name: compliance-baseimage
      description: base image to run most of the built-in pipeline code
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"

    - name: detect-secrets-image
      default: "wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/detect-secrets:0.13.1.ibm.31.dss@sha256:972a827e988f6443f478b7443dc0c8d8761ec15127588103817bb168667ebd0c"
    - name: cra-discovery-image
      default: "icr.io/continuous-delivery/cra-discovery:release.1724@sha256:cf6468d215cbc0b46b534f9956598d599911d15a133eeafe37ba1ae401e9947c"
    - name: cra-vulnerability-image
      default: "icr.io/continuous-delivery/cra-vulnerability:release.1768@sha256:e465f1c6e83ca3b506a7551a3d51eac711f8fe295091577ce003213c66118689"
    - name: cra-cis-check-image
      default: "icr.io/continuous-delivery/cra-cis:release.1639@sha256:b271300acb43f3177db5ba9b08d003e15834c9b4132fcd88bffa6a42db38ac83"
    - name: cra-comm-editor-image
      default: "icr.io/continuous-delivery/cra-comm-editor:release.1519@sha256:703b7a394298fdcaf9e3592b32250a52430b72b858444c96b2e4979759e7b9c6"

  workspaces:
    - name: artifacts
      mountPath: /artifacts

  volumes:
    - name: one-pipeline
      emptyDir: {}
    - name: pipelinectl
      emptyDir: {}
    - name: config
      emptyDir: {}
    - name: dind-certs
      emptyDir: {}
    - name: environment-properties
      configMap:
        name: environment-properties
    - name: secure-properties
      secret:
        secretName: secure-properties
    - name: toolchain
      configMap:
        name: toolchain

  stepTemplate:
    env:
      - name: ONE_PIPELINE_PATH
        value: "/opt/one-pipeline"
      - name: WORKSPACE
        value: "$(workspaces.artifacts.path)"
      - name: TRIGGER_PAYLOAD
        valueFrom:
          configMapKeyRef:
            name: trigger
            key: payload.json
      - name: PIPELINE_RUN_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['tekton.dev/pipelineRun']
      - name: PIPELINE_RUN_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
      - name: PIPELINE_RUN_URL
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-run-url']
      - name: BUILD_NUMBER
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
      - name: PIPELINE_ID
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-id']
      - name: TRIGGER_TYPE
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-type']
      - name: TRIGGER_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-name']
      - name: TRIGGERED_BY
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
      - name: DOCKER_HOST
        value: tcp://localhost:2376
      - name: DOCKER_TLS_VERIFY
        value: '1'
      - name: DOCKER_CERT_PATH
        value: /certs/client

  sidecars:
    - name: dind
      image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/docker:19-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: ENABLE_DIND
          value: "true"
      volumeMounts:
        - name: dind-certs
          mountPath: /certs/client
      script: |
        if [[ "$ENABLE_DIND" == "true" ]]; then
          if [[ $(df -PT /var/lib/docker | awk 'NR==2 {print $2}') == virtiofs ]]; then
            apk add e2fsprogs
            truncate -s 50G /tmp/disk.img
            mkfs.ext4 /tmp/disk.img
            mount /tmp/disk.img /var/lib/docker
          fi
          # Set the MTU to a value that is containable in the ibmcloud calico mtu value
          # References:
          # - https://liejuntao001.medium.com/fix-docker-in-docker-network-issue-in-kubernetes-cc18c229d9e5
          # - https://cloud.ibm.com/docs/containers?topic=containers-kernel#calico-mtu
          #
          /usr/local/bin/dockerd-entrypoint.sh --mtu=1400
        else
          mkdir -p /certs/client
          touch /certs/client/ca.pem
        fi
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ['ls', '/certs/client/ca.pem']

  steps:

    - name: prepare
      image: $(params.compliance-baseimage)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /usr/share/one-pipeline
        - name: pipelinectl
          mountPath: /usr/share/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
      script: |
        #!/bin/bash

        set -e

        if [[ "$PIPELINE_DEBUG" == 1 ]]; then
          set -x
          trap env EXIT
        fi

        while read file; do
          ln -snf "$file" "/config/$(basename "$file")"
        done < <(find '/config/environment-properties' -type f)

        while read file; do
          ln -snf "$file" "/config/$(basename "$file")"
        done < <(find '/config/secure-properties' -type f)

        cp -r /opt/one-pipeline /usr/share
        cp -r /opt/cocoa/bin /usr/share/cocoa

        chmod 777 /usr/share/cocoa/bin

    - name: detect-secrets
      image: $(params.detect-secrets-image)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /opt/one-pipeline
        - name: pipelinectl
          mountPath: /opt/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
      script: |
        #!/bin/sh

        export PATH="$PATH:/opt/cocoa/bin"

        ${ONE_PIPELINE_PATH}/internal/detect-secrets/run

    - name: cra-discovery
      image: $(params.cra-discovery-image)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /opt/one-pipeline
        - name: pipelinectl
          mountPath: /opt/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
        - name: dind-certs
          mountPath: /certs/client
      script: |
        #!/bin/bash

        export PATH="$PATH:/opt/cocoa/bin"

        . ${ONE_PIPELINE_PATH}/internal/cra/discovery

    - name: cra-remediation
      image: $(params.cra-vulnerability-image)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /opt/one-pipeline
        - name: pipelinectl
          mountPath: /opt/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
        - name: dind-certs
          mountPath: /certs/client
      script: |
        #!/bin/bash

        export PATH="$PATH:/opt/cocoa/bin"

        . "${ONE_PIPELINE_PATH}"/internal/cra/remediation

    - name: cra-remediation-comment
      image: $(params.cra-comm-editor-image)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /opt/one-pipeline
        - name: pipelinectl
          mountPath: /opt/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
        - name: dind-certs
          mountPath: /certs/client
      script: |
        #!/bin/bash

        export PATH="$PATH:/opt/cocoa/bin"

        . "${ONE_PIPELINE_PATH}"/internal/cra/comment_editor

    - name: cra-cis-check
      image: $(params.cra-cis-check-image)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /opt/one-pipeline
        - name: pipelinectl
          mountPath: /opt/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
        - name: dind-certs
          mountPath: /certs/client
      script: |
        #!/bin/bash

        export PATH="$PATH:/opt/cocoa/bin"

        . "${ONE_PIPELINE_PATH}"/internal/cra/cis-check

    - name: cra-cis-check-comment
      image: $(params.cra-comm-editor-image)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: one-pipeline
          mountPath: /opt/one-pipeline
        - name: pipelinectl
          mountPath: /opt/cocoa
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
        - name: dind-certs
          mountPath: /certs/client
      script: |
        #!/bin/bash

        export PATH="$PATH:/opt/cocoa/bin"

        . "${ONE_PIPELINE_PATH}"/internal/cra/comment_editor

    - name: finish
      image: $(params.compliance-baseimage)
      workingDir: $(workspaces.artifacts.path)
      volumeMounts:
        - name: config
          mountPath: /config
        - name: environment-properties
          mountPath: /config/environment-properties
        - name: secure-properties
          mountPath: /config/secure-properties
        - name: toolchain
          mountPath: /toolchain
      script: |
        #!/bin/bash

        export PATH="$PATH:/opt/cocoa/bin"

        . "${ONE_PIPELINE_PATH}"/internal/pr_compliance_checks
