---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
  - name: registry-namespace
    description: The namespace in the container image registry. You can set it up
      with {bx cr namespace-add]. Learn more at https://cloud.ibm.com/docs/services/Registry?topic=registry-getting-started#getting-started.
  - name: repo
    description: GIT_REPO
  - name: vault-name
    description: Specify the Key Protect instance name, where the image signing keys
      have been stored. The build and validation signer fields contain default names
      for these signers. The values must match the values created in the Key-Management-Admin-Template.
      See https://github.com/open-toolchain/key-management-admin-toolchain
  - name: repository
    description: The git repo
  - name: app-name
    description: The name of your app
  - name: revision
    description: the branch for the git repo
  - name: registry-region
    description: The IBM Cloud region for image registry
  - name: api-key
    description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
      Service API and interact with the cluster. You can obtain your API key with
      'ic iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
      by clicking **Create API key** (Each API key only can be viewed once).
  - name: apikey
    description: the ibmcloud api key
  - name: cluster-name
    description: the name of the cluster to target
  - name: dev-resource-group
    description: Resource Group
  - name: dev-region
    description: target region
  - name: validation-signer
    description: VALIDATION_SIGNER
  - name: build-signer
    description: BUILD_SIGNER
  - name: branch
    description: the branch for the git repo
  - name: imageUrl
    description: The image url in your container registry
  - name: dev-cluster-namespace
    description: namespace dev
  - name: repository-integration
    description: the repo integration name
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.api-key)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: image-to-build
      spec:
        type: image
        params:
        - name: url
          value: $(params.imageUrl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: $(params.cluster-name)
      spec:
        type: cluster
        params:
          - name: name
            value: $(params.cluster-name)
          - name: username
            value: norealvalueneeded
          - name: url
            value: https://no.real.value.needed
          - name: token
            value: norealvalueneeded
          - name: cadata
            value: norealvalueneeded
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        resources:
          - name: app-image
            resourceRef:
              name: image-to-build
          - name: target-cluster
            resourceRef:
              name: $(params.cluster-name)
        params:
        - name: pipeline-pvc
          value: pipelinerun-$(uid)-pvc
        - name: pipelineRunId
          value: $(uid)
        - name: registry-namespace
          value: $(params.registry-namespace)
        - name: repo
          value: $(params.repo)
        - name: vault-name
          value: $(params.vault-name)
        - name: repository
          value: $(params.repository)
        - name: app-name
          value: $(params.app-name)
        - name: revision
          value: $(params.revision)
        - name: registry-region
          value: $(params.registry-region)
        - name: api-key
          value: $(params.api-key)
        - name: dev-region
          value: $(params.dev-region)
        - name: dev-resource-group
          value: $(params.dev-resource-group)
        - name: validation-signer
          value: $(params.validation-signer)
        - name: build-signer
          value: $(params.build-signer)
        - name: branch
          value: $(params.branch)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: dev-cluster-namespace
          value: $(params.dev-cluster-namespace)
        - name: repository-integration
          value: $(params.repository-integration)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
  - name: revision
    value: master
  - name: branch
    value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: pr-binding
spec:
  params:
  - name: branch
    value: $(event.pull_request.head.ref)
  - name: target-branch
    value: $(event.pull_request.base.ref)
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
  - binding:
      name: binding
    template:
      name: template
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pr-listener
spec:
  triggers:
    - binding:
        name: pr-binding
      template:
        name: pr-template
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: branch
    - name: target-branch
      description: target branch
    - name: repository-integration
      description: the repo integration name
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.api-key)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pr-pipeline
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: pipelineRunId
            value: $(uid)
          - name: target-branch
            value: $(params.target-branch)
          - name: api-key
            value: $(params.api-key)
          - name: repository-integration
            value: $(params.repository-integration)
