---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: pre-build-task
spec:
  inputs:
    params:
    - name: task-pvc
      description: pipeline pvc name place holder
    - name: pipeline-id
      description: id of the pipeline run
    - name: registry-namespace
      description: The namespace in the container image registry. You can set it up
        with {bx cr namespace-add]. Learn more at https://cloud.ibm.com/docs/services/Registry?topic=registry-getting-started#getting-started.
    - name: build-cluster-namespace
      description: Cluster namespace
    - name: build-cluster-name
      description: Build Cluster
    - name: repo
      description: GIT_REPO
    - name: prod-cluster-namespace
      description: Cluster namespace
    - name: build-region
      description: Build region
    - name: vault_name
      description: Specify the Key Protect instance name, where the image signing
        keys have been stored. The build and validation signer fields contain default
        names for these signers. The values must match the values created in the Key-Management-Admin-Template.
        See https://github.com/open-toolchain/key-management-admin-toolchain
    - name: repository
      description: The git repo
    - name: prod-region
      description: Cluster region
    - name: app-name
      description: The name of your app
    - name: revision
      description: the branch for the git repo
    - name: prod-cluster-name
      description: Cluster name
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: api-key
      description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
        Service API and interact with the cluster. You can obtain your API key with
        'bx iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
        by clicking **Create API key** (Each API key only can be viewed once).
    - name: prod-resource-group
      description: Resource Group
    - name: build-resource-group
      description: Build Resource Group
    - name: validation_signer
      description: VALIDATION_SIGNER
    - name: build_signer
      description: BUILD_SIGNER
    - name: evidence-locker
      description: evidence locker for the app
  steps:
  - name: unit-tests
    image: ibmcom/pipeline-base-image:latest
    env:
    - name: VAULT_INSTANCE
      value: $(inputs.params.vault_name)
    - name: VALIDATION_SIGNER
      value: $(inputs.params.validation_signer)
    - name: BUILD_REGION_ID
      value: $(inputs.params.prod-region)
    - name: REGISTRY_REGION_ID
      value: $(inputs.params.registry-region)
    - name: BUILD_RESOURCE_GROUP
      value: $(inputs.params.prod-resource-group)
    - name: BUILD_CLUSTER_NAMESPACE
      value: $(inputs.params.build-cluster-namespace)
    - name: APP_NAME
      value: $(inputs.params.app-name)
    - name: REGISTRY_NAMESPACE
      value: $(inputs.params.registry-namespace)
    - name: GIT_REPO
      value: $(inputs.params.repo)
    - name: PROD_CLUSTER_NAMESPACE
      value: $(inputs.params.prod-cluster-namespace)
    - name: API_KEY
      value: $(inputs.params.api-key)
    - name: PROD_CLUSTER_NAME
      value: $(inputs.params.prod-cluster-name)
    - name: PROD_RESOURCE_GROUP
      value: $(inputs.params.prod-resource-group)
    - name: BUILD_CLUSTER_NAME
      value: $(inputs.params.prod-cluster-name)
    - name: BUILD_SIGNER
      value: $(inputs.params.build_signer)
    - name: PROD_REGION_ID
      value: $(inputs.params.prod-region)
    - name: EVIDENCE_LOCKER_REPO
      value: $(inputs.params.evidence-locker)
    command: ["/bin/bash", "-c"]
    args:
    - |
      #!/bin/bash
      # GIT_URL=$(echo "https://github.ibm.com/padraic-edwards/${app-name}.git" | sed -e "s/:\/\//:\/\/padraic-edwards:$GHE_TOKEN@/g")
      # echo $GIT_URL
      # git clone $GIT_URL .
 
      set -x
      echo "RUNNING"
      TOOLCHAIN_REGION=$(jq -r '.region_id' /cd-config/toolchain.json | awk -F: '{print $3}')
      ibmcloud login -r $TOOLCHAIN_REGION --apikey $API_KEY
      TOKEN=$(ibmcloud iam oauth-tokens --output JSON | jq -r '.iam_token')
      source /artifacts/build.properties
      PIPELINE_RUN_ID=$(inputs.params.pipeline-id)
      
      set -e -o pipefail
      export HOME=/root && source ~/.nvm/nvm.sh
      echo "Cloning ${app-name}"
      echo "Cloning 1 ${REPO}"
      echo "Cloning ${GIT_URL}"
      git clone ${GIT_URL}
      cd ${REPO}
      npm install --save-dev start-server-and-test
      npm install
      npm run ci
      
      cat report
      function collect-evidence () {
        set -e
        local evidence_name=$1
        local evidence_status=$2
        local evidence_details=$3
        jsonContent=$(jq -Rs '.' $evidence_details)
        local evidence_path="raw/ci/${PIPELINE_RUN_ID}/${evidence_name}.json"
        local content="{ \"commit_sha\": \"$GIT_COMMIT\", \"status\": \"$evidence_status\", \"details\": \"$jsonContent\", \"job_id\": \"$PIPELINE_RUN_ID\" }"
        echo $content $evidence_path
        local encoded_content=$(echo "$content" | base64 -w 0)

        if [ -z "$evidence_name" ]; then
          echo "Evidence name must be provided"
          return 1
        fi

        if [ -z "$evidence_status" ]; then
          echo "Evidence status must be provided"
          return 1
        fi

        if [ -z "$evidence_details" ]; then
          echo "Evidence details must be provided"
          return 1
        fi

        if [ -z "$PIPELINE_RUN_ID" ]; then
          echo "PIPELINE_RUN_ID must be provided"
          return 1
        fi

        if [ -z "$GIT_COMMIT" ]; then
          echo "GIT_COMMIT must be provided"
          return 1
        fi

        if [ -z "$EVIDENCE_LOCKER_REPO" ]; then
          echo "EVIDENCE_LOCKER_REPO must be provided"
          return 1
        fi

        if [ -z "$GHE_TOKEN" ]; then
          echo "GHE_TOKEN must be provided"
          return 1
        fi

        echo "Uploading evidence ${evidence_name} for job ${PIPELINE_RUN_ID}"

        curl https://github.ibm.com/api/v3/repos/${EVIDENCE_LOCKER_REPO}/contents/${evidence_path} \
          -d "{\"content\":\"${encoded_content}\",\"message\":\"Upload ${evidence_name} for ${PIPELINE_RUN_ID}\"}" \
          -H "Authorization: Bearer ${GHE_TOKEN}" \
          -H "Content-Type: application/json" \
          -X PUT
      }

      collect-evidence unit-tests passed report
    volumeMounts:
    - mountPath: /artifacts
      name: task-volume
    - mountPath: /cd-config
      name: cd-config-volume
    - mountPath: /steps
      name: steps-volume
  - name: dependency-analysis-placeholder
    image: ibmcom/pipeline-base-image:latest
    env:
    - name: REPOSITORY
      value: $(inputs.params.repository)
    - name: REVISION
      value: $(inputs.params.revision)
    command: ["/bin/sh", "-c"]
    args:
    - |
      #!/bin/bash
      echo "RUNNING Dependency Analysis"
  volumes:
  - name: task-volume
    persistentVolumeClaim:
      claimName: $(inputs.params.task-pvc)
  - name: steps-volume
  - name: cd-config-volume
    configMap:
      name: toolchain
      items:
      - key: toolchain.json
        path: toolchain.json
