---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helper-pipeline
spec:
  params:
    - name: api-key
      description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
        Service API and interact with the cluster. You can obtain your API key with
        'ic iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
        by clicking **Create API key** (Each API key only can be viewed once).
    - name: vault-instance
      description: the vault instance name
    - name: dev-region
      description: the target region
    - name: dev-resource-group
      description: Resource Group
    - name: key-name
      description: the signer entry

  workspaces:
    - name: artifacts

  tasks:
    - name: extract-public-key
      taskRef:
        name: ciso-extract-key
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: vault-instance
          value: $(params.vault-instance)
        - name: region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
        - name: key-name
          value: $(params.validation-signer)
