---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helper-pipeline
spec:
  params:
    - name: api-key
      description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
        Service API and interact with the cluster. You can obtain your API key with
        'ic iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
        by clicking **Create API key** (Each API key only can be viewed once).
    - name: vault-name
      description: Specify the Key Protect instance name, where the image signing keys
        have been stored. The build and validation signer fields contain default names
        for these signers. The values must match the values created in the Key-Management-Admin-Template.
        See https://github.com/open-toolchain/key-management-admin-toolchain
    - name: dev-region
      description: the target region
    - name: dev-resource-group
      description: Resource Group
    - name: validation-signer
      description: the validation signer

  workspaces:
    - name: artifacts

  tasks:
    - name: extract-public-key
      taskRef:
        name: ciso-extract-key
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: vault-name
          value: $(params.vault-name)
        - name: region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
        - name: validation-signer
          value: $(params.validation-signer)
