---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helper-pipeline
spec:
  params:
    - name: vault-instance
      description: the vault instance name
    - name: dev-region
      description: the target region
    - name: dev-resource-group
      description: Resource Group

  workspaces:
    - name: artifacts

  tasks:
    - name: extract-public-key
      taskRef:
        name: ciso-extract-key
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: vault-instance
          value: $(params.vault-instance)
        - name: region
          value: $(params.dev-region)
        - name: resource-group
          value: $(params.dev-resource-group)
