---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: branch
      description: the branch for the git repo
      default: "master"
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: the timestamp of when the commit pushed
    - name: pr-url
      description: pr url
      default: ""
    - name: repository-integration
      description: the repo integration name
    - name: repository
      description: app repository owner and name

    - name: compliance-baseimage
      description: one-pipeline baseimage to run most of the built-in pipeline code
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"

  workspaces:
    - name: artifacts

  tasks:

    - name: code-ci-start
      taskRef:
        name: ci-start
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: branch
          value: $(params.branch)
        - name: repository-integration
          value: $(params.repository-integration)
        - name: commit-id
          value: $(params.commit-id)
        - name: commit-timestamp
          value: $(params.commit-timestamp)
        - name: pr-url
          value: $(params.pr-url)
        - name: repository
          value: $(params.repository)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: setup

    - name: code-setup
      taskRef:
        name: run-stage
      runAfter:
        - code-ci-start
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: setup
        - name: image
          value: $(tasks.code-ci-start.results.image)
        - name: script
          value: $(tasks.code-ci-start.results.script)
        - name: configmap
          value: $(tasks.code-ci-start.results.configmap)
        - name: secret
          value: $(tasks.code-ci-start.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-ci-start.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-ci-start.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-ci-start.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: test

    - name: code-unit-tests
      taskRef:
        name: run-stage
      runAfter:
        - code-setup
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: test
        - name: image
          value: $(tasks.code-setup.results.image)
        - name: script
          value: $(tasks.code-setup.results.script)
        - name: configmap
          value: $(tasks.code-setup.results.configmap)
        - name: secret
          value: $(tasks.code-setup.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-setup.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-setup.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-setup.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: code-ci-compliance
      taskRef:
        name: ci-compliance
      runAfter:
        - code-unit-tests
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: containerize

    - name: build-containerize
      taskRef:
        name: run-stage
      runAfter:
        - code-ci-compliance
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: containerize
        - name: image
          value: $(tasks.code-ci-compliance.results.image)
        - name: script
          value: $(tasks.code-ci-compliance.results.script)
        - name: configmap
          value: $(tasks.code-ci-compliance.results.configmap)
        - name: secret
          value: $(tasks.code-ci-compliance.results.secret)
        - name: abort-on-failure
          value: $(tasks.code-ci-compliance.results.abort-on-failure)
        - name: dind
          value: $(tasks.code-ci-compliance.results.dind)
        - name: image-pull-policy
          value: $(tasks.code-ci-compliance.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: scan-artifact

    - name: build-scan-artifact
      taskRef:
        name: run-stage
      runAfter:
        - build-containerize
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: scan-artifact
        - name: image
          value: $(tasks.build-containerize.results.image)
        - name: script
          value: $(tasks.build-containerize.results.script)
        - name: configmap
          value: $(tasks.build-containerize.results.configmap)
        - name: secret
          value: $(tasks.build-containerize.results.secret)
        - name: abort-on-failure
          value: $(tasks.build-containerize.results.abort-on-failure)
        - name: dind
          value: $(tasks.build-containerize.results.dind)
        - name: image-pull-policy
          value: $(tasks.build-containerize.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: sign-artifact

    - name: build-sign-artifact
      taskRef:
        name: run-stage
      runAfter:
        - build-scan-artifact
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: sign-artifact
        - name: image
          value: $(tasks.build-scan-artifact.results.image)
        - name: script
          value: $(tasks.build-scan-artifact.results.script)
        - name: configmap
          value: $(tasks.build-scan-artifact.results.configmap)
        - name: secret
          value: $(tasks.build-scan-artifact.results.secret)
        - name: abort-on-failure
          value: $(tasks.build-scan-artifact.results.abort-on-failure)
        - name: dind
          value: $(tasks.build-scan-artifact.results.dind)
        - name: image-pull-policy
          value: $(tasks.build-scan-artifact.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: deploy

    - name: deploy-dev
      taskRef:
        name: run-stage
      runAfter:
        - build-sign-artifact
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: deploy
        - name: image
          value: $(tasks.build-sign-artifact.results.image)
        - name: script
          value: $(tasks.build-sign-artifact.results.script)
        - name: configmap
          value: $(tasks.build-sign-artifact.results.configmap)
        - name: secret
          value: $(tasks.build-sign-artifact.results.secret)
        - name: abort-on-failure
          value: $(tasks.build-sign-artifact.results.abort-on-failure)
        - name: dind
          value: $(tasks.build-sign-artifact.results.dind)
        - name: image-pull-policy
          value: $(tasks.build-sign-artifact.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: acceptance-test

    - name: deploy-acceptance-tests
      taskRef:
        name: run-stage
      runAfter:
        - deploy-dev
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: acceptance-test
        - name: image
          value: $(tasks.deploy-dev.results.image)
        - name: script
          value: $(tasks.deploy-dev.results.script)
        - name: configmap
          value: $(tasks.deploy-dev.results.configmap)
        - name: secret
          value: $(tasks.deploy-dev.results.secret)
        - name: abort-on-failure
          value: $(tasks.deploy-dev.results.abort-on-failure)
        - name: dind
          value: $(tasks.deploy-dev.results.dind)
        - name: image-pull-policy
          value: $(tasks.deploy-dev.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: next-stage
          value: release

    - name: deploy-release
      runAfter:
        - deploy-acceptance-tests
      taskRef:
        name: run-stage
      workspaces:
        - name: app
          workspace: artifacts
      params:
        - name: stage
          value: release
        - name: image
          value: $(tasks.deploy-acceptance-tests.results.image)
        - name: script
          value: $(tasks.deploy-acceptance-tests.results.script)
        - name: configmap
          value: $(tasks.deploy-acceptance-tests.results.configmap)
        - name: secret
          value: $(tasks.deploy-acceptance-tests.results.secret)
        - name: abort-on-failure
          value: $(tasks.deploy-acceptance-tests.results.abort-on-failure)
        - name: dind
          value: $(tasks.deploy-acceptance-tests.results.dind)
        - name: image-pull-policy
          value: $(tasks.deploy-acceptance-tests.results.image-pull-policy)
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)

    - name: code-ci-finish
      taskRef:
        name: ci-finish
      runAfter:
        - deploy-release
      workspaces:
        - name: artifacts
          workspace: artifacts
      params:
        - name: compliance-baseimage
          value: $(params.compliance-baseimage)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
