---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: registry-namespace
      description: The namespace in the container image registry. You can set it up
        with {bx cr namespace-add]. Learn more at https://cloud.ibm.com/docs/services/Registry?topic=registry-getting-started#getting-started.
    - name: app-name
      description: The name of your app
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: dev-resource-group
      description: Resource Group
    - name: dev-region
      description: target region
    - name: branch
      description: the branch for the git repo
    - name: repository-integration
      description: the repo integration name
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: the timestamp of when the commit pushed
    - name: slack-notifications
      description: toggles slack notifications
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: inventory-repo
      description: inventory repository owner and name
    - name: version
      description: cr branch name
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: onepipeline-dockerconfigjson
      description: dockerconfigjson for images used in .one-pipeline.yaml
      default: "eyJhdXRocyI6e319" # ie. {"auths":{}} base64 encoded
    - name: cos-bucket-name
      description: Bucket name in your Cloud Object Storage instance, used as an Evidence Locker
      default: ""
    - name: cos-endpoint
      description: Endpoint of your Cloud Object Storage instance, used as an Evidence Locker
      default: ""
    - name: doi-toolchain-id
      description: toolchain ID
    - name: doi-environment
      description: doi target environment, this can be overridden
      default: ""
    - name: one-pipeline-config
      description: Configuration file to be used to customize pipeline behavior
      default: .one-pipeline.yaml
    - name: one-pipeline-config-repo
      description: repository url of the one-pipeline config
    - name: one-pipeline-config-branch
      description: the branch of the one-pipeline config
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.onepipeline-dockerconfigjson)
      metadata:
        name: onepipeline-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
        - name: onepipeline-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: app-name
            value: $(params.app-name)
          - name: registry-region
            value: $(params.registry-region)
          - name: dev-region
            value: $(params.dev-region)
          - name: dev-resource-group
            value: $(params.dev-resource-group)
          - name: branch
            value: $(params.branch)
          - name: repository-integration
            value: $(params.repository-integration)
          - name: slack-notifications
            value: $(params.slack-notifications)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: commit-id
            value: $(params.commit-id)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: inventory-repo
            value: $(params.inventory-repo)
          - name: version
            value: $(params.version)
          - name: cos-bucket-name
            value: "$(params.cos-bucket-name)"
          - name: cos-endpoint
            value: "$(params.cos-endpoint)"
          - name: doi-toolchain-id
            value: $(params.doi-toolchain-id)
          - name: doi-environment
            value: $(params.doi-environment)
          - name: one-pipeline-config
            value: $(params.one-pipeline-config)
          - name: one-pipeline-config-repo
            value: $(params.one-pipeline-config-repo)
          - name: one-pipeline-config-branch
            value: $(params.one-pipeline-config-branch)
        serviceAccountName: sa-pullsecret
