---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: registry-namespace
      description: The namespace in the container image registry. You can set it up
        with {bx cr namespace-add]. Learn more at https://cloud.ibm.com/docs/services/Registry?topic=registry-getting-started#getting-started.
    - name: vault-secret
      description: the vault-secret for signing
    - name: repository
      description: The git repo
    - name: app-name
      description: The name of your app
    - name: registry-region
      description: The IBM Cloud region for image registry
    - name: api-key
      description: The IBM Cloud API key is used to access the IBM Cloud Kubernetes
        Service API and interact with the cluster. You can obtain your API key with
        'ic iam api-key-create' or via the console at https://cloud.ibm.com/iam#/apikeys
        by clicking **Create API key** (Each API key only can be viewed once).
    - name: cluster-name
      description: the name of the cluster to target
    - name: dev-resource-group
      description: Resource Group
    - name: dev-region
      description: target region
    - name: branch
      description: the branch for the git repo
    - name: dev-cluster-namespace
      description: namespace dev
    - name: repository-integration
      description: the repo integration name
    - name: evidence-repo
      description: evidence repo
    - name: issues-repo
      description: incident issues repo
    - name: commit-id
      description: commit id
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
    - name: inventory-repo
      description: inventory repository owner and name
    - name: version
      description: cr branch name
    - name: artifactory-dockerconfigjson
      description: dockerconfigjson for pullsecrets
    - name: slack-notifications
      description: toggles slack notifications
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.api-key)
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(params.artifactory-dockerconfigjson)
      metadata:
        name: artifactory-pull-secret
      type: kubernetes.io/dockerconfigjson
    - apiVersion: v1
      kind: ServiceAccount
      imagePullSecrets:
        - name: artifactory-pull-secret
      metadata:
        name: sa-pullsecret
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: registry-namespace
            value: $(params.registry-namespace)
          - name: vault-secret
            value: $(params.vault-secret)
          - name: repository
            value: $(params.repository)
          - name: app-name
            value: $(params.app-name)
          - name: registry-region
            value: $(params.registry-region)
          - name: api-key
            value: $(params.api-key)
          - name: dev-region
            value: $(params.dev-region)
          - name: dev-resource-group
            value: $(params.dev-resource-group)
          - name: branch
            value: $(params.branch)
          - name: cluster-name
            value: $(params.cluster-name)
          - name: dev-cluster-namespace
            value: $(params.dev-cluster-namespace)
          - name: repository-integration
            value: $(params.repository-integration)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: commit-id
            value: $(params.commit-id)
          - name: evidence-repo
            value: $(params.evidence-repo)
          - name: inventory-repo
            value: $(params.inventory-repo)
          - name: issues-repo
            value: $(params.issues-repo)
          - name: version
            value: $(params.version)
          - name: slack-notifications
            value: $(params.slack-notifications)
        serviceAccountName: sa-pullsecret
