---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-signature-from-file
spec:
  params:
    - name: file

  workspaces:
    - name: artifacts

  results:
    - name: signature

  steps:
    - name: get-signature
      image: ibmcom/pipeline-base-image:2.7
      script: |
        #!/usr/bin/env bash

        RESULT=$(cat "$(workspaces.artifacts.path)/$(params.file)" | jq -r '.content' )
        echo -n $RESULT > $(results.signature.path)
