---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: log-artifact
spec:
  params:
    - name: artifact-path
      description: Path of the artifact file on the workspace to log in to the pipeline
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"

  workspaces:
    - name: artifacts
      mountPath: /artifacts

  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)

  steps:
    - name: log-artifact
      image: ibmcom/pipeline-base-image:2.7
      workingDir: /artifacts
      env:
        - name: ARTIFACT_PATH
          value: $(params.artifact-path)
      script: |
        #!/bin/bash
        set -e -o pipefail;

        if [ "$PIPELINE_DEBUG" == 1 ]; then
          env
          trap env EXIT
          set -x
        fi

        echo "Reading file /artifacts/${ARTIFACT_PATH} ..."

        if [ -f "/artifacts/${ARTIFACT_PATH}" ]; then
          cat "/artifacts/${ARTIFACT_PATH}"
        else
          echo "File was not found!"
        fi
