---
inputs:
  - type: git
    branch: master
    service: ${PIPELINE_REPO}
    path: definitions
triggers:
  - type: git
    name: Git CI Trigger
    service: ${APP_REPO}
    branch: master
    properties:
      - name: app-name
        type: text
        value: ${APP_NAME}
    events:
      push: true
    eventListener: ci-listener
  - type: timer
    name: Git CI Timed Trigger
    eventListener: ci-listener
    disabled: ${GIT_CI_TIMED_TRIGGER_DISABLE}
    cron: "0 4 * * *"
  - type: manual
    name: Manual Trigger
    eventListener: ci-listener
    properties:
      - name: app-name
        type: single_select
        value:
          "${APP_NAME}": true
      - name: repository
        type: INTEGRATION
        value: app-repo
        path: parameters.repo_url
properties:
  - name: inventory-repo
    value: inventory-repo
    type: INTEGRATION
    path: parameters.repo_url
  - name: evidence-repo
    value: evidence-repo
    type: INTEGRATION
    path: parameters.repo_url
  - name: incident-repo
    value: issues-repo
    type: INTEGRATION
    path: parameters.repo_url
  - name: ibmcloud-api-key
    value: ${API_KEY}
    type: SECURE
  - name: vault-secret
    value: ${VAULT_SECRET}
    type: SECURE
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: dev-cluster-namespace
    value: ${DEV_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${DEV_REGION_ID}
    type: text
  - name: cluster-name
    value: ${DEV_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${DEV_RESOURCE_GROUP}
    type: text
  - name: repository-integration
    value: app-repo
    type: text
  - name: artifactory-dockerconfigjson
    value: artifactoryComp
    type: INTEGRATION
    path: parameters.docker_config_json
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
  - name: version
    value: v1
    type: text
  - name: doi-toolchain-id
    value: ${DOI_TOOLCHAIN_ID}
    type: text
  - name: doi-environment
    value: ${DOI_ENVIRONMENT}
    type: text
  - name: cos-endpoint
    value: ${COS_ENDPOINT}
    type: text
  - name: cos-bucket-name
    value: ${COS_BUCKET_NAME}
    type: text
  - name: cos-api-key
    value: ${COS_API_KEY}
    type: SECURE
  - name: one-pipeline-config
    value: ${ONE_PIPELINE_CONFIG}
    type: text
  - name: one-pipeline-config-repo
    value: ${ONE_PIPELINE_CONFIG_REPO}
    type: text
  - name: one-pipeline-config-branch
    value: ${ONE_PIPELINE_CONFIG_BRANCH}
    type: text
  - name: git-token
    value: ${GIT_TOKEN}
    type: SECURE
  - name: slack-notifications
    value: ${SLACK_ENABLED}
    type: text
  - name: custom-image-tag
    type: text
  - name: onepipeline-dockerconfigjson
    value: ${ONE_PIPELINE_DOCKER_CONFIG_JSON}
    type: SECURE
private_worker: ${PRIVATE_WORKER}
