---
inputs:
  - type: git
    branch: ciso-extract-key-test
    service: ${PIPELINE_REPO}
    path: .ci-pipeline
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/git
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/compliance-checks
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/ciso
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/iks
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/container-registry
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/dct
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/inventory
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/gitsecure
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/github
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/evidence
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/util
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/toolchain
  - type: git
    branch: feature-test
    service: ${TEKTON_CATALOG_REPO}
    path: preview/devops-insights
triggers:
  - type: git
    name: Git CI Trigger
    service: ${APP_REPO}
    branch: ciso-testing
    events:
      push: true
    eventListener: listener
  - type: manual
    name: Manual Trigger
    eventListener: listener
properties:
  - name: api-key
    value: ${API_KEY}
    type: SECURE
  - name: evidence-repo
    value: ${EVIDENCE_REPO}
    type: text
  - name: issues-repo
    value: ${ISSUES_REPO}
    type: text
  - name: revision
    value: master
    type: text
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: dev-cluster-namespace
    value: ${DEV_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${DEV_REGION_ID}
    type: text
  - name: cluster-name
    value: ${DEV_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${DEV_RESOURCE_GROUP}
    type: text
  - name: build-signer
    value: ${BUILD_SIGNER}
    type: text
  - name: validation-signer
    value: ${VALIDATION_SIGNER}
    type: text
  - name: vault-name
    value: ${VAULT_INSTANCE}
    type: text
  - name: repository-integration
    value: app-repo
    type: text
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: repository
    value: ${APP_REPO_FULL}
    type: text
  - name: pipeline-debug
    value: "0"
    type: text
  - name: version
    value: v1
    type: text
private_worker: ${PRIVATE_WORKER}
