---
inputs:
  - type: git
    branch: develop
    service: ${PIPELINE_REPO}
    path: .ci-pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/iks
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/container-registry
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/gitsecure
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/slack
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/github-check-statuses/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/inventory-update-version/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/compliance-detect-secrets/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/pipeline-evaluate/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/git-clone/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/git-get-credentials/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/configmap/retry-command/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/configmap/compliance-helper-scripts/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/compliance-collector/2
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/compliance-doi-reporter/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/ciso-image-sign/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/containerize-check-va-scan/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/devops-insights-publish-build/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/devops-insights-publish-deploy/1
triggers:
  - type: git
    name: Git CI Trigger
    service: ${APP_REPO}
    branch: master
    events:
      push: true
    eventListener: listener
  - type: manual
    name: Manual Trigger
    eventListener: listener
properties:
  - name: api-key
    value: ${API_KEY}
    type: SECURE
  - name: vault-secret
    value: ${VAULT_SECRET}
    type: SECURE
  - name: revision
    value: master
    type: text
  - name: registry-region
    value: ${REGISTRY_REGION_ID}
    type: text
  - name: app-name
    value: ${APP_NAME}
    type: text
  - name: registry-namespace
    value: ${REGISTRY_NAMESPACE}
    type: text
  - name: dev-cluster-namespace
    value: ${DEV_CLUSTER_NAMESPACE}
    type: text
  - name: dev-region
    value: ${DEV_REGION_ID}
    type: text
  - name: cluster-name
    value: ${DEV_CLUSTER_NAME}
    type: text
  - name: dev-resource-group
    value: ${DEV_RESOURCE_GROUP}
    type: text
  - name: repository-integration
    value: app-repo
    type: text
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
  - name: version
    value: v1
    type: text
  - name: doi-toolchain-id
    value: ${DOI_TOOLCHAIN_ID}
    type: text
  - name: cos-endpoint
    value: ${COS_ENDPOINT}
    type: text
  - name: cos-bucket-name
    value: ${COS_BUCKET_NAME}
    type: text
  - name: one-pipeline-config
    value: .one-pipeline.yaml
    type: text
  - name: git-token
    value: ""
    type: SECURE
private_worker: ${PRIVATE_WORKER}
