---
inputs:
  - type: git
    branch: feature/add-ciso-support-task
    service: ${DCT_PIPELINE_REPO}
    path: .setup-helper-pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/ciso
triggers:
  - type: manual
    name: Manual Trigger
    eventListener: helper-listener
properties:
  - name: api-key
    value: ${API_KEY}
    type: SECURE
  - name: revision
    value: master
    type: text
  - name: dev-region
    value: ${DEV_REGION_ID}
    type: text
  - name: dev-resource-group
    value: ${DEV_RESOURCE_GROUP}
    type: text
  - name: vault-name
    value: ${VAULT_INSTANCE}
    type: text
  - name: validation-signer
    value: ${VALIDATION_SIGNER}
    type: text
private_worker: ${PRIVATE_WORKER}
