---
inputs:
  - type: git
    branch: develop
    service: ${PIPELINE_REPO}
    path: .pr-pipeline
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: preview/slack
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/github-check-statuses/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/configmap/retry-command/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/toolchain-extract-value/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/git-get-credentials/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/github-set-status/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/compliance-detect-secrets/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/pipeline-evaluate/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/git-clone/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/cra-bom/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/cra-cis-check/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/cra-discovery/1
  - type: git
    branch: master
    service: ${TEKTON_CATALOG_REPO}
    path: stable/task/cra-vulnerability-remediation/1
triggers:
  - type: git
    name: Git PR Trigger
    service: ${APP_REPO}
    branch: master
    events:
      pull_request: true
    eventListener: pr-listener
  - type: manual
    name: Manual Trigger
    eventListener: manual-pr-listener
    properties:
      - name: branch
        type: text
        value: ""
      - name: target-branch
        type: text
        value: "master"
      - name: pr-repository
        type: text
        value: ${PR_REPOSITORY}
      - name: pr-url
        type: text
        value: ""
      - name: commit-id
        type: text
        value: ""
      - name: commit-timestamp
        type: text
        value: ""
properties:
  - name: api-key
    value: ${API_KEY}
    type: SECURE
  - name: pipeline-debug
    value: "0"
    type: text
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: one-pipeline-config
    value: ${ONE_PIPELINE_CONFIG}
    type: text
  - name: one-pipeline-config-repo
    value: ${ONE_PIPELINE_CONFIG_REPO}
    type: text
  - name: one-pipeline-config-branch
    value: ${ONE_PIPELINE_CONFIG_BRANCH}
    type: text
  - name: git-token
    value: ${GIT_TOKEN}
    type: SECURE
  - name: slack-notifications
    value: "0"
    type: text
  - name: onepipeline-dockerconfigjson
    value: ${ONE_PIPELINE_DOCKER_CONFIG_JSON}
    type: SECURE
