---
inputs:
  - type: git
    branch: feat/redesign
    service: ${PIPELINE_REPO}
    path: .pr-pipeline
triggers:
  - type: git
    name: Git PR Trigger
    service: ${APP_REPO}
    branch: master
    events:
      pull_request: true
    eventListener: pr-listener
  - type: manual
    name: Manual Trigger
    eventListener: manual-pr-listener
    properties:
      - name: branch
        type: text
        value: ""
      - name: target-branch
        type: text
        value: "master"
      - name: pr-repository
        type: text
        value: ${PR_REPOSITORY}
      - name: pr-url
        type: text
        value: ""
      - name: commit-id
        type: text
        value: ""
      - name: commit-timestamp
        type: text
        value: ""
properties:
  - name: ibmcloud-api-key
    value: ${API_KEY}
    type: SECURE
  - name: pipeline-debug
    type: single_select
    value:
      "0": true
      "1": false
  - name: artifactory-dockerconfigjson
    value: ${ARTIFACTORY_DOCKER_CONFIG_JSON}
    type: SECURE
  - name: one-pipeline-config
    value: ${ONE_PIPELINE_CONFIG}
    type: text
  - name: one-pipeline-config-repo
    value: ${ONE_PIPELINE_CONFIG_REPO}
    type: text
  - name: one-pipeline-config-branch
    value: ${ONE_PIPELINE_CONFIG_BRANCH}
    type: text
  - name: git-token
    value: ${GIT_TOKEN}
    type: SECURE
  - name: slack-notifications
    value: ${SLACK_ENABLED}
    type: text
  - name: onepipeline-dockerconfigjson
    value: ${ONE_PIPELINE_DOCKER_CONFIG_JSON}
    type: SECURE
